### ISSUE TITLE
Document init-vault

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamin-cli#2]
> init                Init & config instance with db & storage.
> init-vault      Init & config instance with db & storage.

Both share the same help string and it's not clear what the difference is (by looking at the lamin help output)

**Comment by falexwolf** [comment]
@fredericenard, should we simply remove `init-vault` from the CLI? I also think it's confusing and should be somehow labeled as experimental feature.

**Comment by Zethson** [comment]
Not really relevant anymore
