### ISSUE TITLE
Connect to an instance without installing bionty / wetlab

### ISSUE THREAD

**Issue by rcannood** [laminlabs/lamin-cli#89]
Should be possible to connect to an instance without installing bionty / wetlab?

An R user of `laminr` who doesn't want to authenticate prior to connecting to an instance currently needs to install `lamin-cli` and fetch the instance info by running the following commands:

```bash
pip install lamin-cli
lamin connect laminlabs/lamindata
Rscript -e 'laminr::connect("laminlabs/lamindata")'
```

However, the second command fails if the user does not have wetlab installed:

```bash
$ lamin connect laminlabs/lamindata
ImportError: Python package for 'wetlab' is not installed.
If your package is on PyPI, run `pip install wetlab`
```

Could we change `lamin-cli` such that a user can just install `lamin-cli` instead of `lamindb[bionty,wetlab]` to be able to interact with these instances from R?

**Comment by falexwolf** [comment]
You're absolutely right and I will fix this today.

**Comment by falexwolf** [comment]
(Sorry, it wasn't an issue because people would have all of these things installed; but it really shouldn't be a necessity even when they use the Python API. They might not care about certain parts of the schema.)

**Comment by falexwolf** [comment]
Resolved here:

- https://github.com/laminlabs/lamindb-setup/pull/883

Will be in a release today.

**Comment by rcannood** [comment]
Awesome! Tysm!
